### ISSUE TITLE
Cover download BROKEN

### ISSUE THREAD

**Issue by lavolp3** [lavolp3/spotify-ripper#16]
Cover download is broken due to change to spotipy, needs to be fixed!

**Comment by ufoloko** [comment]
Just for your information on web.py you have function get_cover_image, maybe you can use this to retrieve the cover image

**Comment by lavolp3** [comment]
I know, I wrote that :-)
Wanted to switch to spotipy for fetching the cover but got distracted and didn't finish it. For now I'll revert back to the old way through the web api which seems to work.

**Comment by lavolp3** [comment]
issue solved with latest update
