### ISSUE TITLE
default_config_folder is broken for mac or linux

### ISSUE THREAD

**Issue by ufoloko** [lavolp3/spotify-ripper#17]
I noticed that you made changes to install on pi, changing home folder but installation is broken for mac or other SO. If i return back to last version is working again. Just for your information.

**Comment by lavolp3** [comment]
Thanks for the info! 
Need to see if I can manage that. The only solution coming to my mind is checking for raspbian OS and changing installation path only then.

**Comment by lavolp3** [comment]
solved by PR #18
