### ISSUE TITLE
downloading list.txt only repeatitly tries last item

### ISSUE THREAD

**Issue by kaefert** [lavolp3/spotify-ripper#19]
Hey there!

It looks like a build from your repository will only download the last line from a txt file with one spotify-link per line for me. It reads all the links and creates the directories for everything but downloads only the last line.

That functionality works fine using that repository:
https://github.com/wolfmanx/spotify-ripper/tree/pr-collect

**Comment by lavolp3** [comment]
Thanks I'll have a look into it.

**Comment by lavolp3** [comment]
should be solved now. Reverted deletion of an apparently vital line of code :-)

**Comment by kaefert** [comment]
perfect, can confirm the fix works, thank you! :)
