### ISSUE TITLE
genres parameter doesn't work (for me)

### ISSUE THREAD

**Issue by kaefert** [lavolp3/spotify-ripper#20]
I added the parameter "--genres album" but only get those 3 lines for any track downloaded with it:

Attempting to retrieve genres from Spotify's Web API
https://api.spotify.com/v1/albums/{{{ID}}}
URL returned non-200 HTTP code: 401

gonna try "--genres artist" next, let's see if that makes a difference.

**Comment by lavolp3** [comment]
Honestly I have never tried genres.
Will have a look into it. Thanks for sending in the issue

**Comment by kaefert** [comment]
Thank you for continuing development and even supporting this very useful piece of software :)

Just wanted to report that I tried with "--genres artist" too, and got nearly the same result, just different URL to reflect artist instead of album:
```
Attempting to retrieve genres from Spotify's Web API
https://api.spotify.com/v1/artists/{{{ID}}}
URL returned non-200 HTTP code: 401
```

**Comment by lavolp3** [comment]
The web api saves the genre now as part of the album (album.genre) and apparently does not offer an own call anymore. I will try to divert this to a spotipy call since I'm not common to libspotify. But it will take some time.

**Comment by lavolp3** [comment]
The genre property of albums is empty be default apparently according to this issue :-(
https://github.com/spotify/web-api/issues/157
I found that out AFTER I fixed it :-)
I could extract the genre array of the artist, but not sure if that is helpful. 
This would save the genre array of the artist into the track.

Can be quite a lot as in one of my favourite bands:
```
  "genres": [
    "alternative metal",
    "gothenburg metal",
    "groove metal",
    "melodic death metal",
    "melodic metalcore",
    "metal",
    "nu metal",
    "swedish death metal",
    "swedish metal"
  ],
```

What do you think?

**Comment by kaefert** [comment]
Nice, yeah sure genres of Artist would be helpful too, less specific than album but still nice! :)
Did you connect it to the "--genres artist" parameter?

**Comment by lavolp3** [comment]
Should work now.
Please note to use the `--genres` flag WITHOUT any further option. Since there is only the artist's genre available I removed that.

**Comment by kaefert** [comment]
thank you! tested it, works perfect! :)
