### ISSUE TITLE
spotipy intergration

### ISSUE THREAD

**Issue by ramonskie** [lavolp3/spotify-ripper#7]
spotipy is currenly useless as the following is commented out
https://github.com/lavolp3/spotify-ripper/blob/master/spotify_ripper/spotipy_integration.py#L14

after that i still can't get it to work as the a redirect to purple is opend but nothing happens.
how are you using it?

**Comment by ramonskie** [comment]
the best approach here would be.
user logins in.
browser return token
and callback uri is being accepted in the console.

this removed the step of users having to copy/paste urls

**Comment by ramonskie** [comment]
i have researched it for 30 minutes but im also terrible at python..

**Comment by lavolp3** [comment]
Hi ramonskie, can you help me out here?
I've (finally) tried out the oauth route by properly installing and starting the ripper.
I've used my fork including the 
I get the message about the authorization and callback domain. No problem.
Then there is the message: "Enter the url you were redirected to: "
Here I cannot put in anything in my console.
I'm logged in via ssh to a RasPi but that shouldn't make a difference.
Do you know where the problem might be?

**Comment by lavolp3** [comment]
sorry my bad, solved it. The input is just not shown.
It's Friday...

**Comment by lavolp3** [comment]
Spotipy integration is fixed for now.
Setting SPOTIFY credentials as environment variables does not work for some reason.
But setting them in the "spotipy_integration.py" file does work.
Now working on merging the web API calls into spotipy calls to have only one API routine.
